// The Feature directory: every feature in one searchable list. Each entry
// says what it is for, who can use it, where to find it, what must exist
// first, the steps, a screenshot, and related features (by id).

export type FeatureArea = 'Basics' | 'Maintenance' | 'Assets & places' | 'Operations' | 'Inventory & finance' | 'IoT' | 'People & settings';

export interface Feature {
  id: string;
  name: string;
  area: FeatureArea;
  purpose: string;
  who: string;
  where: string;
  /** In-app route, for the "Open this page" button. */
  path?: string;
  prereq: string[];
  steps: string[];
  screenshot?: string;
  guide: string;
  related: string[];
  keywords?: string[];
}

const S = (name: string) => `/help/screens/${name}.webp`;
const ADMIN_MANAGER = 'Administrators and Managers';
const STAFF = 'Administrators, Managers and Technicians';

export const FEATURES: Feature[] = [
  // ---------------------------------------------------------------- Basics
  { id: 'sign-in', name: 'Sign in & accounts', area: 'Basics', purpose: 'Get into FacilityPro securely, reset a forgotten password or create an account.', who: 'Everyone', where: 'Sign-in page', prereq: ['An email address'], steps: ['Enter your email and password.', 'Tick Keep me logged in only on your own device.', 'Click Sign in — or Forgot password? to reset.'], screenshot: S('signin'), guide: '/help/guide/getting-started#signing-in', related: ['two-factor', 'onboarding'], keywords: ['login', 'password', 'log in'] },
  { id: 'onboarding', name: 'Organisation setup', area: 'Basics', purpose: 'Create a new organisation with its name, industry and logo.', who: 'Whoever signs up without an invitation (becomes Administrator)', where: 'Shown after sign-up', prereq: ['A confirmed account'], steps: ['Enter the organisation name and industry.', 'Upload a logo (optional).', 'Click Let’s start planning.'], guide: '/help/guide/getting-started#setting-up-a-new-organisation', related: ['dashboard', 'settings-general'], keywords: ['new organisation', 'company'] },
  { id: 'dashboard', name: 'Dashboard', area: 'Basics', purpose: 'See workload, overdue work, weekly trends and recent activity at a glance.', who: 'Staff and vendors', where: 'Menu → Dashboard', path: '/', prereq: [], steps: ['Read the four key numbers and the overdue banner.', 'Check Weekly and Category charts.', 'Open a request from Recent Activity.'], screenshot: S('dashboard'), guide: '/help/guide/dashboard', related: ['create-menu', 'work-orders', 'reports'], keywords: ['home', 'overview', 'kpi'] },
  { id: 'create-menu', name: 'Create menu & quick add', area: 'Basics', purpose: 'Report a fault or add an asset, part, location, vendor, plan or checklist from one button.', who: ADMIN_MANAGER, where: 'Dashboard → Create', path: '/', prereq: [], steps: ['Click Create.', 'Choose what to add.', 'Fill in the short form; click Add another to keep going.'], screenshot: S('dashboard-create'), guide: '/help/guide/dashboard#the-create-menu', related: ['assets', 'parts', 'locations', 'vendors'] },
  { id: 'tour', name: 'Guided tour', area: 'Basics', purpose: 'A one-minute walk-through of the screen for new users.', who: 'Everyone', where: '? Help → Take the tour', prereq: [], steps: ['Click ? Help, then Take the tour.', 'Use Next and Previous, or Skip tour.', 'Tick Don’t show this tour again to stop it starting by itself.'], screenshot: S('tour'), guide: '/help/guide/getting-started#help-on-every-page', related: ['page-help'], keywords: ['onboarding tour', 'walkthrough'] },
  { id: 'page-help', name: '? Help on every page', area: 'Basics', purpose: 'Explains the page you are on: what it does, what you can do, what the fields mean.', who: 'Everyone', where: 'Top bar → ? Help', prereq: [], steps: ['Click ? Help.', 'Read the panel.', 'Click Read the full guide for more.'], screenshot: S('help-drawer'), guide: '/help/guide/getting-started#help-on-every-page', related: ['tour'] },
  { id: 'language', name: 'English / Tiếng Việt', area: 'Basics', purpose: 'Switch the app language.', who: 'Everyone', where: 'Top bar → EN / VI', prereq: [], steps: ['Click EN or VI in the top bar.'], guide: '/help/guide/getting-started#finding-your-way-around', related: ['settings-general'], keywords: ['vietnamese', 'translate'] },
  { id: 'mobile', name: 'Mobile & offline use', area: 'Basics', purpose: 'Use FacilityPro on a phone, even without signal.', who: 'Everyone', where: 'Any page on a phone', prereq: [], steps: ['Open FacilityPro in your phone’s browser.', 'Use the bottom bar for your main pages.', 'Keep working offline; changes send when you reconnect.'], screenshot: S('mobile-dashboard'), guide: '/help/guide/getting-started#using-facilitypro-on-a-phone', related: ['my-work'] },

  // ---------------------------------------------------------------- Maintenance
  { id: 'requests', name: 'Requests (fault reports)', area: 'Maintenance', purpose: 'Collect and triage reports of things that are broken.', who: 'Everyone can report; staff manage', where: 'Menu → Requests', path: '/requests', prereq: ['Locations', 'Fault types (Settings → Catalogs)'], steps: ['Click New request or Create → Report a fault.', 'Fill in summary, fault type, severity, location and description.', 'Submit; staff then create a work order or reject it.'], screenshot: S('requests'), guide: '/help/guide/work-orders#step-1-a-fault-is-reported', related: ['work-orders', 'public-report', 'inbox'], keywords: ['fault', 'ticket', 'complaint', 'report'] },
  { id: 'work-orders', name: 'Work orders', area: 'Maintenance', purpose: 'Plan, assign, carry out and close maintenance jobs with full history and cost.', who: `${ADMIN_MANAGER} manage; Technicians work on their own`, where: 'Menu → Work orders', path: '/work-orders', prereq: ['Team members to assign'], steps: ['Open a work order (or create one from a request).', 'Assign a technician or vendor.', 'Technician: In progress → log parts, labour, checklist → Resolved.', 'Manager: Verified → Closed.'], screenshot: S('wo-detail-top'), guide: '/help/guide/work-orders', related: ['requests', 'my-work', 'approvals', 'checklists', 'job-sheet'], keywords: ['job', 'task', 'wo'] },
  { id: 'my-work', name: 'My work', area: 'Maintenance', purpose: 'The technician’s own list of assigned jobs.', who: 'Technicians (and anyone with assigned work)', where: 'Menu → My work', path: '/my-work', prereq: ['Work assigned to you'], steps: ['Open My work.', 'Tap a job to start and record it.'], screenshot: S('my-work'), guide: '/help/guide/technicians-teams#my-work-for-technicians', related: ['work-orders'] },
  { id: 'job-sheet', name: 'Printable job sheet', area: 'Maintenance', purpose: 'A printable or PDF sheet of a work order with signature lines.', who: STAFF, where: 'Work order → Print job sheet', prereq: ['A work order'], steps: ['Open the work order.', 'Click Print job sheet.', 'Click Print / Save as PDF.'], screenshot: S('job-sheet'), guide: '/help/guide/work-orders#step-3-assigning-the-work', related: ['work-orders'], keywords: ['pdf', 'print'] },
  { id: 'approvals', name: 'Approvals', area: 'Maintenance', purpose: 'Get a decision before costly work goes ahead.', who: `Anyone working the job requests; ${ADMIN_MANAGER} decide`, where: 'Work order → Request approval; Menu → Approvals', path: '/approvals', prereq: ['A work order'], steps: ['On the work order click Request approval.', 'In Approvals, click Approve or Reject.'], screenshot: S('approvals'), guide: '/help/guide/work-orders#approvals-for-expensive-work', related: ['work-orders'] },
  { id: 'preventive-maintenance', name: 'Preventive maintenance schedules', area: 'Maintenance', purpose: 'Create recurring work (by calendar or meter) that turns into work orders automatically.', who: ADMIN_MANAGER, where: 'Menu → Maintenance', path: '/maintenance', prereq: ['Assets', 'Meters for meter-based plans'], steps: ['Click New schedule.', 'Choose asset, trigger, interval, first due date, checklist, assignee, priority.', 'Click Create. Use Generate due now to create due work at once.'], screenshot: S('maintenance'), guide: '/help/guide/preventive-maintenance', related: ['checklists', 'meters', 'parts'], keywords: ['pm', 'planned', 'recurring', 'schedule'] },
  { id: 'checklists', name: 'Checklists & inspections', area: 'Maintenance', purpose: 'Standard inspection steps — pass/fail, values, photos, notes — on work orders and PM.', who: `${ADMIN_MANAGER} create; Technicians fill in`, where: 'Menu → Checklists', path: '/checklists', prereq: [], steps: ['Click New checklist.', 'Add items and choose their type; tick Required.', 'Attach it to a PM schedule or a work order.'], screenshot: S('checklist-template'), guide: '/help/guide/preventive-maintenance#checklists-inspection-templates', related: ['preventive-maintenance', 'work-orders'], keywords: ['inspection', 'audit'] },
  { id: 'workflows', name: 'Workflows & automation', area: 'Maintenance', purpose: 'Automate routing, reminders, emails, surveys and more, and switch on auto-created work orders.', who: ADMIN_MANAGER, where: 'Menu → Workflows', path: '/workflows', prereq: [], steps: ['Tick Auto-create work orders / public reports if wanted.', 'Create workflow: trigger, trigger settings, actions.', 'Save; watch runs in the Workflow library.'], screenshot: S('workflows'), guide: '/help/guide/settings#workflows-automation', related: ['requests', 'work-orders', 'public-report'], keywords: ['automation', 'rule', 'auto assign', 'routing'] },
  { id: 'public-report', name: 'Public fault reporting & QR codes', area: 'Maintenance', purpose: 'Let anyone report a fault from a QR code or link without an account.', who: 'Set up by Administrators and Managers; used by anyone', where: 'Workflows → Automation; Asset → QR code', prereq: ['Allow public fault reports switched on'], steps: ['Tick Allow public fault reports.', 'Print asset QR codes or share the public report link.'], screenshot: S('asset-qr'), guide: '/help/guide/assets#qr-codes-on-equipment', related: ['requests', 'assets'], keywords: ['qr', 'scan', 'sticker'] },

  // ---------------------------------------------------------------- Assets & places
  { id: 'locations', name: 'Locations', area: 'Assets & places', purpose: 'Your site → building → floor → room/zone tree.', who: `${ADMIN_MANAGER} edit; everyone uses`, where: 'Menu → Locations', path: '/locations', prereq: [], steps: ['Click Add site.', 'Add buildings, floors, rooms and zones on each row.'], screenshot: S('locations'), guide: '/help/guide/facilities', related: ['assets', 'desks', 'facility-booking'], keywords: ['site', 'building', 'floor', 'room', 'zone'] },
  { id: 'assets', name: 'Asset register', area: 'Assets & places', purpose: 'Every piece of equipment with details, specifications, history, documents and QR code.', who: `${ADMIN_MANAGER} edit; staff view`, where: 'Menu → Assets', path: '/assets', prereq: ['Locations', 'Asset types'], steps: ['Click Add asset.', 'Fill in name, type, location, serial, warranty, manufacturer, model.', 'Click Create asset.'], screenshot: S('asset-detail'), guide: '/help/guide/assets', related: ['meters', 'preventive-maintenance', 'documents', 'public-report'], keywords: ['equipment', 'register', 'specification'] },
  { id: 'meters', name: 'Meters & readings', area: 'Assets & places', purpose: 'Track usage (hours, trips, km) and trigger meter-based maintenance.', who: STAFF, where: 'Asset → Meters', prereq: ['An asset'], steps: ['Open the asset → Meters → Add meter.', 'Enter a value and click Log reading.'], screenshot: S('asset-meters'), guide: '/help/guide/assets#meters-and-readings', related: ['assets', 'preventive-maintenance', 'iot-devices'], keywords: ['run hours', 'counter'] },
  { id: 'desks', name: 'Desk booking', area: 'Assets & places', purpose: 'Bookable hot desks by zone.', who: STAFF, where: 'Menu → Desks', path: '/desks', prereq: ['A zone in Locations'], steps: ['Click New desk and choose its zone.', 'Under Make a booking choose desk, name and date → Book.'], screenshot: S('desks'), guide: '/help/guide/facilities#desks-hot-desking', related: ['facility-booking', 'locations'], keywords: ['hot desk', 'reservation'] },
  { id: 'facility-booking', name: 'Facility booking', area: 'Assets & places', purpose: 'Book meeting rooms, gyms and other shared facilities.', who: STAFF, where: 'Menu → Facilities', path: '/facilities', prereq: ['Locations'], steps: ['Click New facility.', 'Under Make a booking choose facility, name and date → Book.'], screenshot: S('facilities'), guide: '/help/guide/facilities#facilities-meeting-rooms-gym-bbq-area', related: ['desks'], keywords: ['meeting room', 'reservation'] },

  // ---------------------------------------------------------------- Operations
  { id: 'vendors', name: 'Vendors', area: 'Operations', purpose: 'Contractors and suppliers you work with.', who: `${ADMIN_MANAGER} edit`, where: 'Menu → Vendors', path: '/vendors', prereq: [], steps: ['Click New vendor.', 'Enter name, category, email, phone.'], screenshot: S('vendors'), guide: '/help/guide/vendors', related: ['contracts', 'work-orders', 'purchase-orders'], keywords: ['contractor', 'supplier'] },
  { id: 'contracts', name: 'Contracts & licences', area: 'Operations', purpose: 'Track contracts and certificates with expiry reminders.', who: ADMIN_MANAGER, where: 'Menu → Vendors', path: '/vendors', prereq: ['A vendor (for contracts)'], steps: ['Click New contract or New license.', 'Enter title, vendor/holder, document link, expiry and reminder days.'], screenshot: S('vendors'), guide: '/help/guide/vendors#adding-a-contract', related: ['vendors', 'reports'], keywords: ['expiry', 'certificate', 'permit'] },
  { id: 'permits', name: 'Permits to work', area: 'Operations', purpose: 'Approve hot work, confined-space and other risky work before it starts.', who: STAFF, where: 'Menu → Permits to work', path: '/permits', prereq: [], steps: ['Fill in Create permit: title, area, requester, approver, due date, notes.', 'Set status and click Submit permit.'], screenshot: S('permits'), guide: '/help/guide/vendors#permits-to-work', related: ['vendors', 'work-orders'], keywords: ['ptw', 'hot work', 'safety'] },
  { id: 'documents', name: 'Documents', area: 'Operations', purpose: 'Manuals, SOPs, certificates and reports, linked to assets, vendors or work orders.', who: `${STAFF}; tenants see documents marked Everyone`, where: 'Menu → Documents', path: '/documents', prereq: [], steps: ['Fill in Add a document.', 'Add a link or upload a file.', 'Link it to a record and choose who can see it → Save document.'], screenshot: S('documents'), guide: '/help/guide/vendors#documents', related: ['assets', 'vendors'], keywords: ['manual', 'sop', 'file'] },
  { id: 'attendance', name: 'Technician attendance', area: 'Operations', purpose: 'Check-in / check-out log of technicians on site.', who: STAFF, where: 'Menu → Technician attendance', path: '/attendance', prereq: ['Technicians in the team'], steps: ['Choose technician, site and Checked in / Checked out.', 'Add a note and click Save entry.'], screenshot: S('attendance'), guide: '/help/guide/technicians-teams#technician-attendance', related: ['technician-profiles'], keywords: ['check in', 'timesheet', 'shift'] },
  { id: 'inbox', name: 'Inbox', area: 'Operations', purpose: 'Conversations with tenants on Zalo, WhatsApp, LINE, email and web.', who: STAFF, where: 'Menu → Inbox', path: '/inbox', prereq: ['Channels connected for delivery (Integrations)'], steps: ['Open a conversation.', 'Reply and click Send, or Create work order.'], screenshot: S('inbox'), guide: '/help/guide/notifications#inbox-conversations-with-tenants', related: ['requests', 'integrations'], keywords: ['zalo', 'whatsapp', 'chat', 'message'] },
  { id: 'announcements', name: 'Tenant announcements', area: 'Operations', purpose: 'Publish news to every tenant’s home page.', who: ADMIN_MANAGER, where: 'Menu → Tenant experience', path: '/tenant-experience', prereq: [], steps: ['Enter title, audience and message.', 'Click Publish update.'], screenshot: S('tenant-experience'), guide: '/help/guide/notifications#announcements-to-tenants', related: ['tenant-app'], keywords: ['broadcast', 'notice'] },
  { id: 'surveys', name: 'Surveys', area: 'Operations', purpose: 'Ask tenants for feedback, e.g. after each job.', who: ADMIN_MANAGER, where: 'Menu → Surveys', path: '/surveys', prereq: [], steps: ['Create a survey with questions.', 'Mark it active; send it with a workflow.'], screenshot: S('surveys'), guide: '/help/guide/notifications#surveys', related: ['workflows'], keywords: ['feedback', 'satisfaction', 'csat'] },
  { id: 'tenant-app', name: 'Tenant app (occupants)', area: 'Operations', purpose: 'A simple app for tenants: report a fault, follow requests, read announcements.', who: 'Occupants', where: 'Home, Report a fault, My requests', prereq: ['Invited or joined via a join link'], steps: ['Tap Report a fault and submit.', 'Follow the status under My requests.'], screenshot: S('tenant-home'), guide: '/help/quick-start/occupant', related: ['requests', 'join-links', 'announcements'], keywords: ['occupant', 'resident', 'tenant'] },

  // ---------------------------------------------------------------- Inventory & finance
  { id: 'parts', name: 'Parts & stock', area: 'Inventory & finance', purpose: 'Spare-part stock levels, reorder warnings and usage history.', who: `${ADMIN_MANAGER} manage; Technicians log usage`, where: 'Menu → Parts', path: '/parts', prereq: [], steps: ['Click New part and fill in stock, reorder level, unit cost, supplier.', 'Restock with the quantity box and Restock.', 'Open a row for its transaction history.'], screenshot: S('parts'), guide: '/help/guide/inventory', related: ['purchase-orders', 'work-orders', 'preventive-maintenance'], keywords: ['inventory', 'spares', 'stock', 'reorder'] },
  { id: 'purchase-orders', name: 'Purchase orders', area: 'Inventory & finance', purpose: 'RFQ → PO → Approved → Received, with receipts that update stock.', who: ADMIN_MANAGER, where: 'Menu → Financial → Procurement', path: '/financial', prereq: ['Vendors', 'Parts'], steps: ['Click New PO and add lines.', 'Move it through its statuses.', 'Record the receipt when goods arrive.'], screenshot: S('financial-po'), guide: '/help/guide/inventory#purchase-orders', related: ['parts', 'vendors', 'financials'], keywords: ['po', 'procurement', 'rfq', 'buy'] },
  { id: 'financials', name: 'Financials', area: 'Inventory & finance', purpose: 'Budgets, spend, payments, invoices, rates, cost centers and customers.', who: ADMIN_MANAGER, where: 'Menu → Financial', path: '/financial', prereq: [], steps: ['Set budgets and cost centers.', 'Record expenditures and payments.', 'Review totals at the top and in Reports.'], screenshot: S('financial'), guide: '/help/guide/reports#financial-overview', related: ['purchase-orders', 'reports'], keywords: ['budget', 'cost', 'invoice', 'payment', 'expense'] },
  { id: 'reports', name: 'Reports & exports', area: 'Inventory & finance', purpose: 'Operational and cost metrics, CSV exports and the activity log.', who: ADMIN_MANAGER, where: 'Menu → Reports', path: '/reports', prereq: [], steps: ['Set the filters.', 'Read the metrics and charts.', 'Export requests or work orders to CSV.'], screenshot: S('reports'), guide: '/help/guide/reports', related: ['dashboard', 'financials'], keywords: ['kpi', 'csv', 'excel', 'audit log', 'mtbf'] },
  { id: 'billing', name: 'Billing & plan', area: 'Inventory & finance', purpose: 'Your FacilityPro plan, usage and payment.', who: 'Administrators', where: 'Menu → Billing', path: '/billing', prereq: [], steps: ['Open Billing to see your plan and usage.', 'Upgrade or manage payment.'], screenshot: S('billing'), guide: '/help/guide/settings#billing', related: ['settings-general'], keywords: ['subscription', 'plan', 'pricing'] },

  // ---------------------------------------------------------------- IoT
  { id: 'iot-devices', name: 'IoT devices', area: 'IoT', purpose: 'Connect sensors and meters; see live readings and history.', who: `${ADMIN_MANAGER} add; Technicians view`, where: 'Menu → Devices', path: '/devices', prereq: ['A device or gateway able to send data'], steps: ['Click Add device and follow the steps.', 'Copy the device key into the device.', 'Open the device to see Live data and History.'], screenshot: S('device-detail'), guide: '/help/guide/iot', related: ['iot-alerts', 'iot-rules', 'meters'], keywords: ['sensor', 'mqtt', 'modbus', 'lorawan', 'bacnet', 'telemetry', 'energy'] },
  { id: 'iot-alerts', name: 'IoT alerts', area: 'IoT', purpose: 'Be told when a reading goes out of range or a device goes offline.', who: STAFF, where: 'Devices → Alerts', path: '/devices', prereq: ['Devices with rules'], steps: ['Open the alert.', 'Click Acknowledge, then Resolve with a note.'], screenshot: S('device-alerts'), guide: '/help/guide/iot#alerts', related: ['iot-rules', 'notifications'], keywords: ['alarm', 'offline'] },
  { id: 'iot-rules', name: 'Threshold rules', area: 'IoT', purpose: 'Decide when readings raise alerts, notify people or create work orders.', who: ADMIN_MANAGER, where: 'Device → Rules', prereq: ['A device'], steps: ['Add rule: metric, condition, threshold.', 'Choose action, severity, cooldown and escalation.'], screenshot: S('device-rules'), guide: '/help/guide/iot#threshold-rules', related: ['iot-alerts', 'work-orders'], keywords: ['threshold', 'limit'] },

  // ---------------------------------------------------------------- People & settings
  { id: 'notifications', name: 'Notifications', area: 'People & settings', purpose: 'In-app alerts for assignments, status changes, approvals, stock and IoT, plus email/SMS/push.', who: 'Everyone', where: 'Top bar → bell; Menu → Security', prereq: [], steps: ['Click the bell; click a notification to open it.', 'Choose email, SMS or push under Security.'], screenshot: S('notifications'), guide: '/help/guide/notifications', related: ['two-factor', 'integrations'], keywords: ['bell', 'email', 'sms', 'push', 'alert'] },
  { id: 'team', name: 'Team & roles', area: 'People & settings', purpose: 'Members, their roles, invitations and removal.', who: 'Administrators', where: 'Settings → Team & roles', path: '/settings?tab=team', prereq: [], steps: ['Change a role in the drop-down.', 'Invite a member by email.', 'Remove with the bin.'], screenshot: S('settings-team'), guide: '/help/guide/user-management', related: ['join-links', 'technician-profiles'], keywords: ['users', 'invite', 'permissions', 'role'] },
  { id: 'join-links', name: 'Join links & QR codes', area: 'People & settings', purpose: 'Let many people join with one link or poster.', who: 'Administrators', where: 'Settings → Team & roles', path: '/settings?tab=team', prereq: [], steps: ['Choose the role, name, expiry and max people.', 'Create link, then Share or print its QR code.'], screenshot: S('settings-team'), guide: '/help/guide/user-management#join-links-and-qr-codes', related: ['team', 'tenant-app'], keywords: ['invite link', 'qr'] },
  { id: 'technician-profiles', name: 'Technician profiles & site access', area: 'People & settings', purpose: 'Skills, labour rate, shift, certifications and which sites a person can see.', who: 'Administrators', where: 'Settings → Team & roles → Profile / Site access', path: '/settings?tab=team', prereq: ['The person is a member'], steps: ['Click Profile to edit details and certifications.', 'Click Site access to limit sites.'], guide: '/help/guide/technicians-teams#technician-profiles', related: ['team', 'attendance'], keywords: ['skills', 'rate', 'certification'] },
  { id: 'two-factor', name: 'Two-factor authentication', area: 'People & settings', purpose: 'Protect your account with a code from an authenticator app.', who: 'Everyone', where: 'Menu → Security', path: '/security', prereq: ['An authenticator app'], steps: ['Click Enable 2FA.', 'Scan the QR code, enter the code, Verify & enable.'], screenshot: S('security'), guide: '/help/guide/user-management#your-own-account-security', related: ['sign-in', 'notifications'], keywords: ['2fa', 'mfa', 'security'] },
  { id: 'settings-general', name: 'Organisation settings', area: 'People & settings', purpose: 'Name, default language, timezone, currency and AI sentiment.', who: ADMIN_MANAGER, where: 'Settings → General', path: '/settings', prereq: [], steps: ['Change the fields.', 'Click Save.'], screenshot: S('settings-general'), guide: '/help/guide/settings#general', related: ['catalogs', 'sla'], keywords: ['timezone', 'currency'] },
  { id: 'catalogs', name: 'Fault & asset types', area: 'People & settings', purpose: 'The lists used when reporting faults and adding assets.', who: ADMIN_MANAGER, where: 'Settings → Catalogs', path: '/settings', prereq: [], steps: ['Use + Add, edit, switch off or delete types.', 'Or Load default types.'], screenshot: S('settings-catalogs'), guide: '/help/guide/settings#catalogs', related: ['requests', 'assets'], keywords: ['categories', 'fault type', 'asset type'] },
  { id: 'sla', name: 'SLA targets', area: 'People & settings', purpose: 'Resolution time per priority; sets work-order due dates.', who: ADMIN_MANAGER, where: 'Settings → SLA', path: '/settings', prereq: [], steps: ['Enter hours for each priority.', 'Click Save on the row.'], screenshot: S('settings-sla'), guide: '/help/guide/settings#sla-targets', related: ['work-orders', 'reports'], keywords: ['due date', 'response time'] },
  { id: 'tv-displays', name: 'TV display boards', area: 'People & settings', purpose: 'A live work-order board for a TV or wall screen, no sign-in needed.', who: ADMIN_MANAGER, where: 'Settings → TV displays; Work orders → TV display', path: '/settings', prereq: [], steps: ['Click New display and choose site, columns, priorities, details, layout.', 'Create display and open the link on the TV.'], screenshot: S('settings-displays'), guide: '/help/guide/settings#tv-displays', related: ['work-orders'], keywords: ['screen', 'kiosk', 'wallboard'] },
  { id: 'integrations', name: 'Integrations', area: 'People & settings', purpose: 'IoT, WhatsApp, Zalo and message delivery status.', who: ADMIN_MANAGER, where: 'Settings → Integrations', path: '/settings', prereq: [], steps: ['Check what is connected.', 'Contact support to connect WhatsApp or Zalo.'], screenshot: S('settings-integrations'), guide: '/help/guide/settings#integrations', related: ['inbox', 'iot-devices', 'notifications'] },
  { id: 'support', name: 'Help & support tickets', area: 'People & settings', purpose: 'Ask FacilityPro support a question or report a problem with the app.', who: STAFF, where: 'Menu → Help & support', path: '/support', prereq: [], steps: ['Click New ticket.', 'Choose the type and urgency, describe the problem, Send ticket.'], screenshot: S('support'), guide: '/help/guide/getting-started#help-on-every-page', related: ['page-help'], keywords: ['contact', 'bug', 'question'] },
];

export function featureById(id: string): Feature | undefined {
  return FEATURES.find((f) => f.id === id);
}
