import type { FeatureText } from './features';

// Vietnamese text for the Feature directory, keyed by feature id (see features.ts).
export const FEATURES_VI: Record<string, FeatureText> = {
  // ---------------------------------------------------------------- Basics
  'sign-in': {
    name: 'Đăng nhập & tài khoản',
    purpose: 'Vào FacilityPro an toàn, đặt lại mật khẩu đã quên hoặc tạo tài khoản mới.',
    who: 'Tất cả mọi người',
    where: 'Trang đăng nhập',
    prereq: ['Một địa chỉ email'],
    steps: ['Nhập email và mật khẩu.', 'Chỉ đánh dấu Duy trì đăng nhập trên thiết bị của riêng bạn.', 'Nhấn Đăng nhập — hoặc Quên mật khẩu? để đặt lại.'],
  },
  onboarding: {
    name: 'Thiết lập tổ chức',
    purpose: 'Tạo tổ chức mới với tên, ngành nghề và logo.',
    who: 'Người đăng ký mà không có lời mời (sẽ trở thành Quản trị viên)',
    where: 'Hiển thị sau khi đăng ký',
    prereq: ['Tài khoản đã được xác nhận'],
    steps: ['Nhập tên tổ chức và ngành nghề.', 'Tải logo lên (không bắt buộc).', 'Nhấn Hãy bắt đầu lập kế hoạch.'],
  },
  dashboard: {
    name: 'Bảng điều khiển',
    purpose: 'Xem nhanh khối lượng công việc, việc quá hạn, xu hướng theo tuần và hoạt động gần đây.',
    who: 'Nhân viên và nhà cung cấp',
    where: 'Menu → Bảng điều khiển',
    prereq: [],
    steps: ['Xem bốn chỉ số chính và thanh cảnh báo quá hạn.', 'Xem biểu đồ theo tuần và theo danh mục.', 'Mở một yêu cầu từ mục Hoạt động gần đây.'],
  },
  'create-menu': {
    name: 'Menu Tạo mới & thêm nhanh',
    purpose: 'Báo sự cố hoặc thêm tài sản, phụ tùng, vị trí, nhà cung cấp, kế hoạch hay danh sách kiểm tra chỉ từ một nút.',
    who: 'Quản trị viên và Quản lý',
    where: 'Bảng điều khiển → Tạo mới',
    prereq: [],
    steps: ['Nhấn Tạo mới.', 'Chọn mục cần thêm.', 'Điền biểu mẫu ngắn; nhấn Thêm nữa để tiếp tục thêm.'],
  },
  tour: {
    name: 'Hướng dẫn nhanh',
    purpose: 'Một phút giới thiệu màn hình dành cho người dùng mới.',
    who: 'Tất cả mọi người',
    where: '? Trợ giúp → Xem hướng dẫn nhanh',
    prereq: [],
    steps: ['Nhấn ? Trợ giúp, rồi Xem hướng dẫn nhanh.', 'Dùng Sau và Trước, hoặc Bỏ qua.', 'Đánh dấu Không hiển thị lại hướng dẫn này để hướng dẫn không tự bật nữa.'],
  },
  'page-help': {
    name: '? Trợ giúp trên mọi trang',
    purpose: 'Giải thích trang bạn đang xem: trang dùng để làm gì, bạn có thể làm gì và ý nghĩa của các trường.',
    who: 'Tất cả mọi người',
    where: 'Thanh trên cùng → ? Trợ giúp',
    prereq: [],
    steps: ['Nhấn ? Trợ giúp.', 'Đọc bảng hướng dẫn.', 'Nhấn Đọc hướng dẫn đầy đủ để xem thêm.'],
  },
  language: {
    name: 'English / Tiếng Việt',
    purpose: 'Chuyển đổi ngôn ngữ của ứng dụng.',
    who: 'Tất cả mọi người',
    where: 'Thanh trên cùng → EN / VI',
    prereq: [],
    steps: ['Nhấn EN hoặc VI trên thanh trên cùng.'],
  },
  mobile: {
    name: 'Dùng trên điện thoại & ngoại tuyến',
    purpose: 'Dùng FacilityPro trên điện thoại, kể cả khi không có sóng.',
    who: 'Tất cả mọi người',
    where: 'Mọi trang trên điện thoại',
    prereq: [],
    steps: ['Mở FacilityPro bằng trình duyệt trên điện thoại.', 'Dùng thanh dưới cùng để vào các trang chính.', 'Cứ tiếp tục làm việc khi ngoại tuyến; thay đổi sẽ được gửi khi có kết nối lại.'],
  },

  // ---------------------------------------------------------------- Maintenance
  requests: {
    name: 'Yêu cầu (báo sự cố)',
    purpose: 'Tiếp nhận và phân loại các báo cáo về hư hỏng.',
    who: 'Mọi người đều có thể báo; nhân viên xử lý',
    where: 'Menu → Yêu cầu',
    prereq: ['Vị trí', 'Loại sự cố (Cài đặt → Danh mục)'],
    steps: ['Nhấn Yêu cầu mới hoặc Tạo mới → Báo sự cố.', 'Điền tóm tắt, loại sự cố, mức độ nghiêm trọng, vị trí và mô tả.', 'Gửi đi; sau đó nhân viên sẽ tạo lệnh công việc hoặc từ chối.'],
  },
  'work-orders': {
    name: 'Lệnh công việc',
    purpose: 'Lập kế hoạch, phân công, thực hiện và đóng các công việc bảo trì, kèm đầy đủ lịch sử và chi phí.',
    who: 'Quản trị viên và Quản lý điều hành; Kỹ thuật viên làm việc được giao cho mình',
    where: 'Menu → Lệnh công việc',
    prereq: ['Có thành viên trong nhóm để phân công'],
    steps: ['Mở một lệnh công việc (hoặc tạo từ một yêu cầu).', 'Phân công cho kỹ thuật viên hoặc nhà cung cấp.', 'Kỹ thuật viên: Đang xử lý → ghi phụ tùng, nhân công, danh sách kiểm tra → Đã xử lý.', 'Quản lý: Đã nghiệm thu → Đã đóng.'],
  },
  'my-work': {
    name: 'Công việc của tôi',
    purpose: 'Danh sách công việc được giao cho riêng kỹ thuật viên.',
    who: 'Kỹ thuật viên (và bất kỳ ai được giao việc)',
    where: 'Menu → Công việc của tôi',
    prereq: ['Có công việc được giao cho bạn'],
    steps: ['Mở Công việc của tôi.', 'Chạm vào một công việc để bắt đầu và ghi nhận.'],
  },
  'job-sheet': {
    name: 'Phiếu công việc để in',
    purpose: 'Phiếu in hoặc PDF của một lệnh công việc, có dòng ký tên.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Lệnh công việc → In phiếu công việc',
    prereq: ['Một lệnh công việc'],
    steps: ['Mở lệnh công việc.', 'Nhấn In phiếu công việc.', 'Nhấn In / Lưu PDF.'],
  },
  approvals: {
    name: 'Phê duyệt',
    purpose: 'Xin quyết định trước khi tiến hành công việc tốn kém.',
    who: 'Người thực hiện công việc gửi yêu cầu; Quản trị viên và Quản lý quyết định',
    where: 'Lệnh công việc → Yêu cầu phê duyệt; Menu → Phê duyệt',
    prereq: ['Một lệnh công việc'],
    steps: ['Trên lệnh công việc, nhấn Yêu cầu phê duyệt.', 'Trong Phê duyệt, nhấn Phê duyệt hoặc Từ chối.'],
  },
  'preventive-maintenance': {
    name: 'Lịch bảo trì phòng ngừa',
    purpose: 'Tạo công việc định kỳ (theo lịch hoặc theo đồng hồ) tự động chuyển thành lệnh công việc.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Bảo trì',
    prereq: ['Tài sản', 'Đồng hồ (cho kế hoạch theo đồng hồ)'],
    steps: ['Nhấn Lịch mới.', 'Chọn tài sản, điều kiện kích hoạt, chu kỳ, ngày đến hạn đầu tiên, danh sách kiểm tra, người thực hiện và mức ưu tiên.', 'Nhấn Tạo. Dùng Tạo công việc đến hạn để tạo ngay các công việc đã đến hạn.'],
  },
  checklists: {
    name: 'Danh sách kiểm tra & kiểm định',
    purpose: 'Các bước kiểm tra chuẩn — đạt/không đạt, giá trị, ảnh, ghi chú — trên lệnh công việc và bảo trì phòng ngừa.',
    who: 'Quản trị viên và Quản lý tạo; Kỹ thuật viên điền',
    where: 'Menu → Danh sách kiểm tra',
    prereq: [],
    steps: ['Nhấn Danh sách mới.', 'Thêm các mục và chọn loại; đánh dấu Bắt buộc.', 'Gắn vào lịch bảo trì phòng ngừa hoặc lệnh công việc.'],
  },
  workflows: {
    name: 'Quy trình & tự động hóa',
    purpose: 'Tự động điều phối, nhắc việc, gửi email, khảo sát và nhiều việc khác, đồng thời bật tự động tạo lệnh công việc.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Quy trình',
    prereq: [],
    steps: ['Đánh dấu Tự động tạo lệnh công việc / Cho phép báo cáo sự cố công khai nếu cần.', 'Tạo quy trình: điều kiện kích hoạt, thiết lập điều kiện, hành động.', 'Lưu; theo dõi các lần chạy trong Thư viện quy trình.'],
  },
  'public-report': {
    name: 'Báo sự cố công khai & mã QR',
    purpose: 'Cho phép bất kỳ ai báo sự cố qua mã QR hoặc liên kết mà không cần tài khoản.',
    who: 'Quản trị viên và Quản lý thiết lập; ai cũng dùng được',
    where: 'Quy trình → Tự động hóa; Tài sản → Mã QR',
    prereq: ['Đã bật Cho phép báo cáo sự cố công khai'],
    steps: ['Đánh dấu Cho phép báo cáo sự cố công khai.', 'In mã QR của tài sản hoặc chia sẻ Liên kết báo cáo công khai.'],
  },

  // ---------------------------------------------------------------- Assets & places
  locations: {
    name: 'Vị trí',
    purpose: 'Cây vị trí của bạn: khu vực → tòa nhà → tầng → phòng/khu.',
    who: 'Quản trị viên và Quản lý chỉnh sửa; mọi người đều dùng',
    where: 'Menu → Vị trí',
    prereq: [],
    steps: ['Nhấn Thêm khu vực.', 'Thêm tòa nhà, tầng, phòng và khu trên từng dòng.'],
  },
  assets: {
    name: 'Danh mục tài sản',
    purpose: 'Mọi thiết bị kèm thông tin chi tiết, thông số kỹ thuật, lịch sử, tài liệu và mã QR.',
    who: 'Quản trị viên và Quản lý chỉnh sửa; nhân viên xem',
    where: 'Menu → Tài sản',
    prereq: ['Vị trí', 'Loại tài sản'],
    steps: ['Nhấn Thêm tài sản.', 'Điền tên, loại, vị trí, số sê-ri, bảo hành, nhà sản xuất, model.', 'Nhấn Tạo tài sản.'],
  },
  meters: {
    name: 'Đồng hồ & chỉ số',
    purpose: 'Theo dõi mức sử dụng (giờ chạy, số chuyến, km) và kích hoạt bảo trì theo đồng hồ.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Tài sản → Đồng hồ',
    prereq: ['Một tài sản'],
    steps: ['Mở tài sản → Đồng hồ → Thêm đồng hồ.', 'Nhập giá trị và nhấn Ghi chỉ số.'],
  },
  desks: {
    name: 'Đặt bàn làm việc',
    purpose: 'Bàn làm việc linh hoạt có thể đặt chỗ, theo từng khu.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Bàn làm việc',
    prereq: ['Một khu trong Vị trí'],
    steps: ['Nhấn Bàn mới và chọn khu.', 'Trong Đặt chỗ, chọn bàn, tên và ngày → Đặt.'],
  },
  'facility-booking': {
    name: 'Đặt cơ sở vật chất',
    purpose: 'Đặt phòng họp, phòng gym và các tiện ích dùng chung khác.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Cơ sở vật chất',
    prereq: ['Vị trí'],
    steps: ['Nhấn Cơ sở mới.', 'Trong Đặt chỗ, chọn cơ sở, tên và ngày → Đặt.'],
  },

  // ---------------------------------------------------------------- Operations
  vendors: {
    name: 'Nhà cung cấp',
    purpose: 'Các nhà thầu và nhà cung cấp bạn hợp tác.',
    who: 'Quản trị viên và Quản lý chỉnh sửa',
    where: 'Menu → Nhà cung cấp',
    prereq: [],
    steps: ['Nhấn Nhà cung cấp mới.', 'Nhập tên, danh mục, email, số điện thoại.'],
  },
  contracts: {
    name: 'Hợp đồng & giấy phép',
    purpose: 'Theo dõi hợp đồng và chứng chỉ, có nhắc nhở trước khi hết hạn.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Nhà cung cấp',
    prereq: ['Một nhà cung cấp (đối với hợp đồng)'],
    steps: ['Nhấn Hợp đồng mới hoặc Giấy phép mới.', 'Nhập tiêu đề, nhà cung cấp/người sở hữu, liên kết tài liệu, ngày hết hạn và số ngày nhắc trước.'],
  },
  permits: {
    name: 'Giấy phép làm việc',
    purpose: 'Phê duyệt công việc nóng, làm việc trong không gian hạn chế và các công việc rủi ro khác trước khi bắt đầu.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Giấy phép làm việc',
    prereq: [],
    steps: ['Điền mục Tạo giấy phép: tiêu đề, khu vực, người đề nghị, người phê duyệt, ngày đến hạn, ghi chú.', 'Đặt trạng thái và nhấn Gửi giấy phép.'],
  },
  documents: {
    name: 'Tài liệu',
    purpose: 'Sách hướng dẫn, quy trình vận hành chuẩn (SOP), chứng chỉ và báo cáo, liên kết với tài sản, nhà cung cấp hoặc lệnh công việc.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên; cư dân xem được tài liệu được chia sẻ cho Mọi người',
    where: 'Menu → Tài liệu',
    prereq: [],
    steps: ['Điền mục Thêm tài liệu.', 'Thêm liên kết hoặc tải tệp lên.', 'Liên kết với một bản ghi và chọn ai được xem → Lưu tài liệu.'],
  },
  attendance: {
    name: 'Chấm công kỹ thuật viên',
    purpose: 'Nhật ký vào ca / ra ca của kỹ thuật viên tại công trường.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Chấm công',
    prereq: ['Có kỹ thuật viên trong nhóm'],
    steps: ['Chọn kỹ thuật viên, khu vực và Đã vào ca / Đã ra ca.', 'Thêm ghi chú và nhấn Lưu mục ghi.'],
  },
  inbox: {
    name: 'Hộp thư',
    purpose: 'Trò chuyện với cư dân qua Zalo, WhatsApp, LINE, email và web.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Hộp thư',
    prereq: ['Đã kết nối kênh gửi tin (Tích hợp)'],
    steps: ['Mở một cuộc trò chuyện.', 'Trả lời và nhấn Gửi, hoặc Tạo lệnh công việc.'],
  },
  announcements: {
    name: 'Thông báo cho cư dân',
    purpose: 'Đăng tin lên trang chủ của mọi cư dân.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Trải nghiệm khách thuê',
    prereq: [],
    steps: ['Nhập tiêu đề, đối tượng nhận và nội dung.', 'Nhấn Đăng thông báo.'],
  },
  surveys: {
    name: 'Khảo sát',
    purpose: 'Lấy ý kiến phản hồi của cư dân, ví dụ sau mỗi công việc.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Khảo sát',
    prereq: [],
    steps: ['Tạo khảo sát kèm các câu hỏi.', 'Đặt khảo sát ở trạng thái hoạt động; gửi đi bằng một quy trình.'],
  },
  'tenant-app': {
    name: 'Ứng dụng cho cư dân',
    purpose: 'Ứng dụng đơn giản cho cư dân: báo sự cố, theo dõi yêu cầu, đọc thông báo.',
    who: 'Cư dân',
    where: 'Trang chủ, Báo sự cố, Yêu cầu của tôi',
    prereq: ['Được mời hoặc tham gia qua liên kết tham gia'],
    steps: ['Chạm Báo sự cố và gửi đi.', 'Theo dõi trạng thái trong Yêu cầu của tôi.'],
  },

  // ---------------------------------------------------------------- Inventory & finance
  parts: {
    name: 'Phụ tùng & tồn kho',
    purpose: 'Mức tồn kho phụ tùng, cảnh báo đặt hàng lại và lịch sử sử dụng.',
    who: 'Quản trị viên và Quản lý quản lý; Kỹ thuật viên ghi nhận sử dụng',
    where: 'Menu → Phụ tùng',
    prereq: [],
    steps: ['Nhấn Phụ tùng mới và điền tồn kho, mức đặt hàng lại, đơn giá, nhà cung cấp.', 'Nhập thêm hàng bằng ô số lượng và nút Nhập thêm.', 'Mở một dòng để xem lịch sử giao dịch.'],
  },
  'purchase-orders': {
    name: 'Đơn mua hàng',
    purpose: 'Yêu cầu báo giá → Đơn mua hàng → Đã duyệt → Đã nhận, với phiếu nhận hàng tự cập nhật tồn kho.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Tài chính → Mua sắm',
    prereq: ['Nhà cung cấp', 'Phụ tùng'],
    steps: ['Nhấn Đơn mua hàng mới và thêm các dòng.', 'Chuyển đơn qua từng trạng thái.', 'Ghi nhận phiếu nhận hàng khi hàng về.'],
  },
  financials: {
    name: 'Tài chính',
    purpose: 'Ngân sách, chi tiêu, thanh toán, hóa đơn, đơn giá, trung tâm chi phí và khách hàng.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Tài chính',
    prereq: [],
    steps: ['Thiết lập ngân sách và trung tâm chi phí.', 'Ghi nhận các khoản chi và thanh toán.', 'Xem tổng số ở đầu trang và trong Báo cáo.'],
  },
  reports: {
    name: 'Báo cáo & xuất dữ liệu',
    purpose: 'Chỉ số vận hành và chi phí, xuất CSV và nhật ký hoạt động.',
    who: 'Quản trị viên và Quản lý',
    where: 'Menu → Báo cáo',
    prereq: [],
    steps: ['Đặt bộ lọc.', 'Xem các chỉ số và biểu đồ.', 'Xuất yêu cầu hoặc lệnh công việc ra CSV.'],
  },
  billing: {
    name: 'Thanh toán & gói dịch vụ',
    purpose: 'Gói FacilityPro, mức sử dụng và thanh toán của bạn.',
    who: 'Quản trị viên',
    where: 'Menu → Thanh toán',
    prereq: [],
    steps: ['Mở Thanh toán để xem gói và mức sử dụng.', 'Nâng cấp hoặc quản lý phương thức thanh toán.'],
  },

  // ---------------------------------------------------------------- IoT
  'iot-devices': {
    name: 'Thiết bị IoT',
    purpose: 'Kết nối cảm biến và đồng hồ đo; xem số liệu trực tiếp và lịch sử.',
    who: 'Quản trị viên và Quản lý thêm; Kỹ thuật viên xem',
    where: 'Menu → Thiết bị',
    prereq: ['Một thiết bị hoặc gateway có thể gửi dữ liệu'],
    steps: ['Nhấn Thêm thiết bị và làm theo các bước.', 'Sao chép khóa thiết bị vào thiết bị.', 'Mở thiết bị để xem Dữ liệu trực tiếp và Lịch sử.'],
  },
  'iot-alerts': {
    name: 'Cảnh báo IoT',
    purpose: 'Nhận thông báo khi chỉ số vượt ngưỡng hoặc thiết bị mất kết nối.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Thiết bị → Cảnh báo',
    prereq: ['Thiết bị đã có quy tắc'],
    steps: ['Mở cảnh báo.', 'Nhấn Xác nhận, sau đó Đã xử lý kèm ghi chú.'],
  },
  'iot-rules': {
    name: 'Quy tắc ngưỡng',
    purpose: 'Quyết định khi nào chỉ số sẽ tạo cảnh báo, thông báo cho mọi người hoặc tạo lệnh công việc.',
    who: 'Quản trị viên và Quản lý',
    where: 'Thiết bị → Quy tắc',
    prereq: ['Một thiết bị'],
    steps: ['Thêm quy tắc: chỉ số đo, điều kiện, ngưỡng.', 'Chọn hành động, mức độ nghiêm trọng, thời gian chờ và cấp báo lên.'],
  },

  // ---------------------------------------------------------------- People & settings
  notifications: {
    name: 'Thông báo',
    purpose: 'Thông báo trong ứng dụng về phân công, thay đổi trạng thái, phê duyệt, tồn kho và IoT, cùng email/SMS/push.',
    who: 'Tất cả mọi người',
    where: 'Thanh trên cùng → chuông; Menu → Bảo mật',
    prereq: [],
    steps: ['Nhấn vào chuông; nhấn một thông báo để mở.', 'Chọn email, SMS hoặc push trong Bảo mật.'],
  },
  team: {
    name: 'Nhóm & vai trò',
    purpose: 'Thành viên, vai trò của họ, lời mời và xóa thành viên.',
    who: 'Quản trị viên',
    where: 'Cài đặt → Nhóm & vai trò',
    prereq: [],
    steps: ['Đổi vai trò trong danh sách thả xuống.', 'Mời thành viên qua email.', 'Xóa bằng biểu tượng thùng rác.'],
  },
  'join-links': {
    name: 'Liên kết tham gia & mã QR',
    purpose: 'Cho nhiều người tham gia chỉ bằng một liên kết hoặc một tấm áp phích.',
    who: 'Quản trị viên',
    where: 'Cài đặt → Nhóm & vai trò',
    prereq: [],
    steps: ['Chọn vai trò, tên, thời hạn và số người tối đa.', 'Tạo liên kết, rồi Chia sẻ hoặc in mã QR của liên kết.'],
  },
  'technician-profiles': {
    name: 'Hồ sơ kỹ thuật viên & quyền truy cập khu vực',
    purpose: 'Kỹ năng, đơn giá nhân công, ca làm, chứng chỉ và những khu vực một người được xem.',
    who: 'Quản trị viên',
    where: 'Cài đặt → Nhóm & vai trò → Hồ sơ / Quyền truy cập khu vực',
    prereq: ['Người đó đã là thành viên'],
    steps: ['Nhấn Hồ sơ để sửa thông tin và chứng chỉ.', 'Nhấn Quyền truy cập khu vực để giới hạn khu vực.'],
  },
  'two-factor': {
    name: 'Xác thực hai yếu tố',
    purpose: 'Bảo vệ tài khoản bằng mã từ ứng dụng xác thực.',
    who: 'Tất cả mọi người',
    where: 'Menu → Bảo mật',
    prereq: ['Một ứng dụng xác thực'],
    steps: ['Nhấn Bật 2FA.', 'Quét mã QR, nhập mã, rồi nhấn Xác minh & bật.'],
  },
  'settings-general': {
    name: 'Cài đặt tổ chức',
    purpose: 'Tên, ngôn ngữ mặc định, múi giờ, tiền tệ và phân tích cảm xúc bằng AI.',
    who: 'Quản trị viên và Quản lý',
    where: 'Cài đặt → Chung',
    prereq: [],
    steps: ['Thay đổi các trường.', 'Nhấn Lưu.'],
  },
  catalogs: {
    name: 'Loại sự cố & loại tài sản',
    purpose: 'Các danh sách dùng khi báo sự cố và thêm tài sản.',
    who: 'Quản trị viên và Quản lý',
    where: 'Cài đặt → Danh mục',
    prereq: [],
    steps: ['Dùng + Thêm, sửa, tắt hoặc xóa các loại.', 'Hoặc Tải các loại mặc định.'],
  },
  sla: {
    name: 'Mục tiêu SLA',
    purpose: 'Thời gian xử lý theo từng mức ưu tiên; dùng để đặt ngày đến hạn cho lệnh công việc.',
    who: 'Quản trị viên và Quản lý',
    where: 'Cài đặt → SLA',
    prereq: [],
    steps: ['Nhập số giờ cho từng mức ưu tiên.', 'Nhấn Lưu trên dòng đó.'],
  },
  'tv-displays': {
    name: 'Bảng hiển thị trên TV',
    purpose: 'Bảng lệnh công việc trực tiếp cho TV hoặc màn hình treo tường, không cần đăng nhập.',
    who: 'Quản trị viên và Quản lý',
    where: 'Cài đặt → Màn hình TV; Lệnh công việc → Màn hình TV',
    prereq: [],
    steps: ['Nhấn Màn hình mới và chọn khu vực, cột, mức ưu tiên, thông tin chi tiết, bố cục.', 'Tạo màn hình và mở liên kết trên TV.'],
  },
  integrations: {
    name: 'Tích hợp',
    purpose: 'IoT, WhatsApp, Zalo và trạng thái gửi tin nhắn.',
    who: 'Quản trị viên và Quản lý',
    where: 'Cài đặt → Tích hợp',
    prereq: [],
    steps: ['Kiểm tra những gì đã được kết nối.', 'Liên hệ bộ phận hỗ trợ để kết nối WhatsApp hoặc Zalo.'],
  },
  support: {
    name: 'Trợ giúp & phiếu hỗ trợ',
    purpose: 'Đặt câu hỏi cho bộ phận hỗ trợ FacilityPro hoặc báo lỗi của ứng dụng.',
    who: 'Quản trị viên, Quản lý và Kỹ thuật viên',
    where: 'Menu → Trợ giúp & hỗ trợ',
    prereq: [],
    steps: ['Nhấn Phiếu mới.', 'Chọn loại và mức độ khẩn cấp, mô tả vấn đề, rồi nhấn Gửi phiếu.'],
  },
};

// Labels for FeatureArea values.
export const FEATURE_AREAS_VI: Record<string, string> = {
  Basics: 'Cơ bản',
  Maintenance: 'Bảo trì',
  'Assets & places': 'Tài sản & địa điểm',
  Operations: 'Vận hành',
  'Inventory & finance': 'Kho & tài chính',
  IoT: 'IoT',
  'People & settings': 'Con người & cài đặt',
};
