import type { PageHelp } from './pageHelp';

// "? Help" panel text per page. The first matching entry wins, so put
// role-specific entries before the general one for the same path.

const G = (s: string) => `/help/guide/${s}`;

export const PAGE_HELP: PageHelp[] = [
  {
    patterns: ['/'], roles: ['occupant'], title: 'Home',
    what: 'Your starting point: report a problem in the building and see how your requests are going.',
    canDo: ['Report a fault with a photo', 'See your latest requests and their status', 'Read announcements from building management'],
    fields: [['Report a fault', 'Opens the fault form.'], ['My requests', 'Everything you have reported, newest first.'], ['Announcements', 'News such as planned water or power shut-offs.']],
    guide: '/help/quick-start/occupant',
  },
  {
    patterns: ['/'], title: 'Dashboard',
    what: 'An overview of all maintenance work: how much there is, what is overdue, weekly trends and the latest activity.',
    canDo: ['Create anything from the Create button', 'Search requests', 'Open recent requests', 'Finish the setup To Do List'],
    fields: [['No. of Tasks', 'All work orders.'], ['Pending Tasks', 'Work orders not yet resolved.'], ['No. of Assets', 'Assets in service.'], ['Recently Completed Tasks', 'Work finished in the last 30 days.'], ['Weekly', 'Faults reported vs resolved per day, last 7 days.'], ['Category', 'Faults by type, last 30 days.']],
    tip: 'A red banner above the numbers means some work is overdue.',
    guide: G('dashboard'),
  },
  {
    patterns: ['/requests/new'], title: 'Report a fault',
    what: 'Tell the maintenance team what is wrong and where.',
    canDo: ['Describe the problem', 'Choose where it is and what equipment', 'Attach a photo'],
    fields: [['Summary', 'A short title, e.g. “Pantry sink leaking”.'], ['Fault type', 'The kind of problem; sets the default priority.'], ['Severity', 'How serious it is: Low, Medium, High or Critical.'], ['Location', 'The room or area.'], ['Asset', 'The piece of equipment, if you know it (staff).'], ['Description', 'Anything that helps the technician.'], ['Photo', 'Optional, but very useful.']],
    guide: G('work-orders#step-1-a-fault-is-reported'),
  },
  {
    patterns: ['/requests/:id'], roles: ['occupant'], title: 'Your request',
    what: 'The details and current status of something you reported.',
    canDo: ['Check the status', 'Read what you reported'],
    fields: [['Status', 'New → Assigned → In progress → Resolved → Closed. On hold means waiting; Rejected means it isn’t a maintenance job.']],
    guide: '/help/quick-start/occupant',
  },
  {
    patterns: ['/requests/:id'], title: 'Request details',
    what: 'One reported fault: what, where, who reported it and through which channel.',
    canDo: ['Create a work order from it', 'Change its status (e.g. Rejected)', 'Open the linked work order'],
    fields: [['Channel', 'How it arrived: web, QR code, email, Zalo…'], ['Reported in', 'The language it was written in.'], ['Linked work order', 'The job created from this request.']],
    guide: G('work-orders#step-2-turning-a-request-into-a-work-order'),
  },
  {
    patterns: ['/requests'], title: 'Requests',
    what: 'Every reported fault and service request, newest first.',
    canDo: ['Report a new fault', 'Search by title or description', 'Filter by status and location', 'Open a request'],
    fields: [['Status', 'New, Triaged, Assigned, In progress, On hold, Resolved, Closed or Rejected.'], ['Fault type', 'The category chosen when reporting.']],
    guide: G('work-orders#step-2-turning-a-request-into-a-work-order'),
  },
  {
    patterns: ['/work-orders/:id'], title: 'Work order',
    what: 'One maintenance job from start to finish: who does it, by when, the checklist, parts, labour, photos and how it ended.',
    canDo: ['Move it to the next status', 'Assign a technician or vendor', 'Fill in the checklist', 'Log parts and labour', 'Add before/after photos', 'Request approval', 'Print a job sheet'],
    fields: [['Status', 'Only the next allowed steps are offered. Managers verify, close and reopen.'], ['Assignee', 'The technician responsible; assigning sets the status to Assigned.'], ['Vendor', 'An outside contractor, or In-house.'], ['Due date', 'Set from the SLA target for the priority.'], ['Cost', 'Labour plus parts, updated automatically.'], ['Cause of failure / Completion code', 'Needed before the job can be resolved.'], ['Downtime (minutes)', 'How long the equipment was out of use.']],
    tip: 'Resolving needs a completion code and all required checklist items done.',
    guide: G('work-orders'),
  },
  {
    patterns: ['/work-orders'], title: 'Work orders',
    what: 'All maintenance jobs with their assignee, priority, status and due date.',
    canDo: ['Search by title or instructions', 'Filter by status, location, assignee and priority', 'Open a job', 'Set up a TV display'],
    fields: [['Open (unassigned)', 'Nobody is assigned yet.'], ['Due', 'When it must be resolved (from SLA targets).']],
    guide: G('work-orders#finding-work-orders'),
  },
  {
    patterns: ['/my-work'], title: 'My work',
    what: 'The work orders assigned to you.',
    canDo: ['Open a job and start it', 'Record parts, labour, checklist and photos', 'Resolve it when done'],
    fields: [['Priority', 'Critical and High first.'], ['Status', 'Assigned, In progress, On hold…'], ['Due', 'When it must be finished.']],
    tip: 'No signal? Keep working — changes are sent when you are back online.',
    guide: G('technicians-teams#my-work-for-technicians'),
  },
  {
    patterns: ['/maintenance'], title: 'Preventive maintenance',
    what: 'Recurring planned work. Each schedule creates work orders automatically when it comes due.',
    canDo: ['Create a schedule by calendar or by meter', 'Generate due work now', 'Pause or resume a schedule', 'Set a required parts kit'],
    fields: [['Every N days / units', 'How often the work repeats.'], ['Next due', 'When the next work order is due.'], ['Generate this many days early', 'Lead time: the work order is created this many days before it is due.'], ['Required parts', 'Parts suggested on each generated work order.']],
    guide: G('preventive-maintenance'),
  },
  {
    patterns: ['/checklists', '/checklists/:id'], title: 'Checklists',
    what: 'Reusable inspection templates used on work orders and maintenance schedules.',
    canDo: ['Create a checklist', 'Add Pass/Fail, Value, Photo and Text items', 'Mark items as required'],
    fields: [['Type', 'Pass / Fail, Value (a number), Photo or Text note.'], ['Required', 'Must be done before the work order can be resolved.']],
    guide: G('preventive-maintenance#checklists-inspection-templates'),
  },
  {
    patterns: ['/assets/:id'], title: 'Asset',
    what: 'Everything about one piece of equipment: details, specifications, repair history, meters, documents and QR code.',
    canDo: ['Report a fault on it', 'Edit or retire it (managers)', 'Add meters and log readings', 'Attach documents', 'Print its QR code'],
    fields: [['Warranty until', 'When the manufacturer’s warranty ends.'], ['Specifications', 'Technical data such as capacity and refrigerant.'], ['History', 'All requests and work orders for this asset.'], ['QR code', 'Staff who scan it open this page; others can report a fault.']],
    guide: G('assets#the-asset-page'),
  },
  {
    patterns: ['/assets'], title: 'Assets',
    what: 'The register of all equipment you maintain.',
    canDo: ['Add an asset', 'Filter by type, location and status', 'Open an asset'],
    fields: [['Status', 'In service, or Retired / disposed.'], ['Serial', 'The manufacturer’s serial number.']],
    guide: G('assets'),
  },
  {
    patterns: ['/parts'], title: 'Parts & inventory',
    what: 'Spare parts and consumables with their stock levels.',
    canDo: ['Add a part', 'Restock', 'Filter by category', 'See each part’s transaction history'],
    fields: [['In stock', 'Current quantity.'], ['Reorder at', 'At or below this level the part shows Low stock.'], ['Unit cost', 'Used to cost parts on work orders.']],
    guide: G('inventory'),
  },
  {
    patterns: ['/vendors'], title: 'Vendors & contracts',
    what: 'Contractors and suppliers, their contracts, and your licences and certificates with expiry tracking.',
    canDo: ['Add vendors', 'Add contracts with reminders', 'Add licences and certificates'],
    fields: [['Expiring soon', 'Within its reminder period.'], ['Expired', 'Past its expiry date.'], ['Document URL', 'A link to the signed document.']],
    guide: G('vendors'),
  },
  {
    patterns: ['/locations'], title: 'Locations',
    what: 'Your site → building → floor → room/zone tree. Everything else points to these.',
    canDo: ['Add a site', 'Add buildings, floors, rooms and zones', 'Rename or delete'],
    fields: [['Room', 'An enclosed space, e.g. a plant room.'], ['Zone', 'An open area, e.g. a lobby or car park.']],
    guide: G('facilities'),
  },
  {
    patterns: ['/workflows'], title: 'Workflows',
    what: 'Automations: route and assign work, send reminders, emails and surveys, and turn requests into work orders.',
    canDo: ['Allow public fault reports', 'Auto-create work orders', 'Create a workflow from a trigger and actions', 'Disable or delete a workflow'],
    fields: [['Trigger', 'The event that starts it, e.g. Work Order Created.'], ['Trigger settings', 'Narrow it, e.g. a fault type, priority or minutes pending.'], ['Cooldown', 'Minimum gap between runs.'], ['Actions', 'What happens, e.g. Assign To or Send Email.']],
    guide: G('settings#workflows-automation'),
  },
  {
    patterns: ['/approvals'], title: 'Approvals',
    what: 'Work orders waiting for a decision.',
    canDo: ['Approve', 'Reject'],
    fields: [['Requested by', 'Who asked for the approval, with their note.']],
    tip: 'Approval records the decision; it does not lock the work order.',
    guide: G('work-orders#approvals-for-expensive-work'),
  },
  {
    patterns: ['/inbox'], title: 'Inbox',
    what: 'Conversations with tenants and contacts across Zalo, WhatsApp, LINE, email and web.',
    canDo: ['Read and reply', 'Turn a message into a work order', 'Start a new conversation'],
    fields: [['Delivery', 'sending…, sent, delivered, read or Not delivered.']],
    guide: G('notifications#inbox-conversations-with-tenants'),
  },
  {
    patterns: ['/devices/:id'], title: 'Device',
    what: 'One sensor or meter: live readings, history, alerts, rules and connection.',
    canDo: ['Chart any reading over time', 'Acknowledge and resolve alerts', 'Add threshold rules (managers)', 'Send commands', 'Rotate the device key (managers)'],
    fields: [['Live data', 'Latest value of each reading; stale means it hasn’t reported recently.'], ['Rules', 'Thresholds that raise alerts or create work orders.'], ['Connection', 'Device key and endpoints — keep secret.']],
    guide: G('iot#a-devices-page'),
  },
  {
    patterns: ['/devices'], title: 'Devices',
    what: 'All connected sensors, meters and gateways, and their alerts.',
    canDo: ['Add a device', 'Filter by building, category, manufacturer, protocol', 'See all open alerts'],
    fields: [['Online / Offline', 'Whether it has reported recently.'], ['Warning / Critical', 'Devices with open alerts of that severity.']],
    guide: G('iot'),
  },
  {
    patterns: ['/desks'], title: 'Desks',
    what: 'Bookable hot desks grouped by zone.',
    canDo: ['Add desks', 'Book a desk for a date', 'See recent bookings'],
    fields: [['Zone', 'The area the desk is in (from Locations).']],
    guide: G('facilities#desks-hot-desking'),
  },
  {
    patterns: ['/facilities'], title: 'Facilities',
    what: 'Shared facilities such as meeting rooms, a gym or a BBQ terrace, and their bookings.',
    canDo: ['Add a facility', 'Book it for a date', 'See recent bookings'],
    fields: [['Seats', 'How many people it holds.']],
    guide: G('facilities#facilities-meeting-rooms-gym-bbq-area'),
  },
  {
    patterns: ['/reports'], title: 'Reports',
    what: 'Operational and cost metrics, exports and the activity log.',
    canDo: ['Filter by dates, location, technician and priority', 'Export requests or work orders to CSV', 'See who changed what'],
    fields: [['Avg resolution (hrs)', 'Average hours from creation to resolution.'], ['PM on-time completion', 'Share of planned work done by its due date.'], ['Planned vs. reactive', 'Share of cost from planned work.'], ['Mean time between failures', 'Average days between breakdowns.']],
    guide: G('reports'),
  },
  {
    patterns: ['/financial'], title: 'Financial operations',
    what: 'Purchasing, budgets, spending, payments, rates, customers and cost centers.',
    canDo: ['Create and receive purchase orders', 'Record expenditures and payments', 'Set budgets and cost centers'],
    fields: [['Committed spend', 'Money committed on purchase orders and expenditures.'], ['PO status', 'RFQ → PO → Approved → Received.'], ['Cost center', 'Which building or budget the spend belongs to.']],
    guide: G('reports#financial-overview'),
  },
  {
    patterns: ['/documents'], title: 'Documents',
    what: 'Manuals, SOPs, certificates and reports in one place.',
    canDo: ['Add a link or upload a file', 'Link it to an asset, vendor or work order', 'Choose who can see it'],
    fields: [['Who can see it', 'Staff only, or everyone including tenants.']],
    guide: G('vendors#documents'),
  },
  {
    patterns: ['/permits'], title: 'Permits to work',
    what: 'Approval for risky work before it starts.',
    canDo: ['Create a permit', 'Set its status', 'See all permits'],
    fields: [['Status', 'Draft, Submitted, Approved or Rejected.'], ['Notes', 'The work, hazards and safety controls.']],
    tip: 'Only start the work once the permit is approved.',
    guide: G('vendors#permits-to-work'),
  },
  {
    patterns: ['/attendance'], title: 'Technician attendance',
    what: 'A check-in and check-out log so supervisors know who is on site.',
    canDo: ['Log a check-in or check-out', 'See the latest entries'],
    fields: [['Action', 'Checked in or Checked out.'], ['Site / location', 'Where they are.']],
    guide: G('technicians-teams#technician-attendance'),
  },
  {
    patterns: ['/tenant-experience'], title: 'Tenant experience',
    what: 'Announcements shown on every tenant’s home page.',
    canDo: ['Publish an update', 'See past announcements'],
    fields: [['Audience', 'A label only; published updates go to all tenants.'], ['Draft', 'Not shown to tenants.']],
    guide: G('notifications#announcements-to-tenants'),
  },
  {
    patterns: ['/surveys'], title: 'Surveys',
    what: 'Feedback questionnaires for tenants.',
    canDo: ['Create a survey', 'Activate or deactivate it', 'Send it with a workflow'],
    fields: [],
    guide: G('notifications#surveys'),
  },
  {
    patterns: ['/security'], title: 'Security',
    what: 'Protect your account and choose how you are notified.',
    canDo: ['Enable two-factor authentication', 'Turn email, SMS or push notifications on or off'],
    fields: [['Two-factor authentication', 'Asks for a code from an authenticator app at sign-in.'], ['Mobile number', 'Include the country code, e.g. +84…']],
    guide: G('user-management#your-own-account-security'),
  },
  {
    patterns: ['/settings'], title: 'Settings',
    what: 'How FacilityPro works for your organisation.',
    canDo: ['General: name, language, timezone, currency', 'Catalogs: fault and asset types', 'SLA: resolution targets', 'Team & roles: people and invitations', 'TV displays', 'Integrations'],
    fields: [['Timezone', 'Used for due dates and schedules.'], ['Currency', 'Three-letter code, e.g. VND.'], ['SLA hours', 'Sets each new work order’s due date by priority.']],
    guide: G('settings'),
  },
  {
    patterns: ['/billing'], title: 'Billing',
    what: 'Your FacilityPro plan, usage and payments.',
    canDo: ['See your plan and limits', 'Upgrade or manage payment'],
    fields: [],
    guide: G('settings#billing'),
  },
  {
    patterns: ['/help', '/help/:id', '/help/:id/:id'], title: 'Help Center',
    what: 'Step-by-step guides with screenshots, a searchable feature directory and quick-start guides for each role.',
    canDo: ['Search all help', 'Read a guide section', 'Browse the feature directory', 'Take the tour'],
    fields: [],
    guide: '/help',
  },
];
